In [1]:
import pandas as pd
import pickle

In [2]:
with open('../raw_data/test_df.pickle', 'rb') as f:
            test_df = pickle.load(f)

In [3]:
with open('../raw_data/train_df.pickle', 'rb') as g:
    train_df = pickle.load(g)

In [4]:
test_df.head(3)

,precinct_number,offense_type,crime_completed,offense_level,premise_desc,premise,jurisdiction,park_name,suspect_age,suspect_race,...,latitude,longitude,metro,victim_age,victim_race,victim_sex,period,borough,patrol_borough,six_hour_date
55,75,CRIMINAL MISCHIEF & RELATED OF,COMPLETED,MISDEMEANOR,REAR OF,FACTORY/WAREHOUSE,N.Y. POLICE DEPT,NOT PARK,UNKNOWN,BLACK,...,40.663657,-73.901087,NOT SUBWAY,UNKNOWN,UNKNOWN,D,2016-08-12 03:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2016-08-12 00:00:00
203,75,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,FRONT OF,RESIDENCE - APT. HOUSE,N.Y. POLICE DEPT,NOT PARK,25-44,WHITE HISPANIC,...,40.673450,-73.885434,NOT SUBWAY,25-44,UNKNOWN,F,2017-05-07 20:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2017-05-07 18:00:00
268,75,CRIMINAL MISCHIEF & RELATED OF,COMPLETED,MISDEMEANOR,FRONT OF,CLOTHING/BOUTIQUE,N.Y. POLICE DEPT,NOT PARK,UNKNOWN,UNKNOWN,...,40.681223,-73.880658,NOT SUBWAY,UNKNOWN,UNKNOWN,D,2016-02-13 17:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2016-02-13 12:00:00

In [5]:
train_df.head(3)

,precinct_number,offense_type,crime_completed,offense_level,premise_desc,premise,jurisdiction,park_name,suspect_age,suspect_race,...,latitude,longitude,metro,victim_age,victim_race,victim_sex,period,borough,patrol_borough,six_hour_date
73,75,DANGEROUS DRUGS,COMPLETED,MISDEMEANOR,UNKNOWN,OTHER,N.Y. POLICE DEPT,NOT PARK,UNKNOWN,UNKNOWN,...,40.666027,-73.896318,NOT SUBWAY,UNKNOWN,UNKNOWN,E,2015-04-12 18:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2015-04-12 18:00:00
99,75,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,INSIDE,RESIDENCE - APT. HOUSE,N.Y. POLICE DEPT,NOT PARK,UNKNOWN,UNKNOWN,...,40.679690,-73.866463,NOT SUBWAY,45-64,WHITE HISPANIC,F,2012-08-31 12:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2012-08-31 12:00:00
251,75,PETIT LARCENY,COMPLETED,MISDEMEANOR,INSIDE,CHAIN STORE,N.Y. POLICE DEPT,NOT PARK,UNKNOWN,UNKNOWN,...,40.651701,-73.868447,NOT SUBWAY,UNKNOWN,UNKNOWN,D,2013-04-03 14:00:00,BROOKLYN,PATROL BORO BKLYN NORTH,2013-04-03 12:00:00

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149575 entries, 73 to 6983160
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   precinct_number  149575 non-null  int64
 1   offense_type     149575 non-null  object
 2   crime_completed  149575 non-null  object
 3   offense_level    149575 non-null  object
 4   premise_desc     149575 non-null  object
 5   premise          149575 non-null  object
 6   jurisdiction     149575 non-null  object
 7   park_name        149575 non-null  object
 8   suspect_age      149575 non-null  object
 9   suspect_race     149575 non-null  object
 10  suspect_sex      149575 non-null  object
 11  latitude         149575 non-null  float64
 12  longitude        149575 non-null  float64
 13  metro            149575 non-null  object
 14  victim_age       149575 non-null  object
 15  victim_race      149575 non-null  object
 16  victim_sex       149575 non-null  object
 17  period           149575 non-null  object
 18  borough          149575 non-null  object
 19  patrol_borough   149575 non-null  object
 20  six_hour_date    149575 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(17)
memory usage: 25.1+ MB

In [7]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56942 entries, 55 to 6983184
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   precinct_number  56942 non-null  int64
 1   offense_type     56942 non-null  object
 2   crime_completed  56942 non-null  object
 3   offense_level    56942 non-null  object
 4   premise_desc     56942 non-null  object
 5   premise          56942 non-null  object
 6   jurisdiction     56942 non-null  object
 7   park_name        56942 non-null  object
 8   suspect_age      56942 non-null  object
 9   suspect_race     56942 non-null  object
 10  suspect_sex      56942 non-null  object
 11  latitude         56942 non-null  float64
 12  longitude        56942 non-null  float64
 13  metro            56942 non-null  object
 14  victim_age       56942 non-null  object
 15  victim_race      56942 non-null  object
 16  victim_sex       56942 non-null  object
 17  period           56942 non-null  object
 18  borough          56942 non-null  object
 19  patrol_borough   56942 non-null  object
 20  six_hour_date    56942 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(17)
memory usage: 9.6+ MB